language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.1
  - jruby-9.1.2.0
before_install:
  - gem update --system
  - gem --version # make sure rubygems actually were updated
  - ./test/setup_litmus.sh
before_script:
  - rm -rf /tmp/dav-file-store
  - mkdir /tmp/dav-file-store
script: ./test/run.sh
